SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS occupancies;
DROP TABLE IF EXISTS parking_slots;
DROP TABLE IF EXISTS community_memberships;
DROP TABLE IF EXISTS communities;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;
